include "conveyor-local-beta.conf"
include "conveyor.conf"

app {
    fsname = alchitry-labs-beta
    long-fsname = alchitry-labs-beta
    display-name = Alchitry Labs Beta
    rdns-name = com.alchitry.labs2.beta

    vcs-url = github.com/alchitry/Alchitry-Labs-V2-Beta
    icons = "icons/preview_icon.svg"

    jvm {
        system-properties {
            "app.release.channel" = "beta"
        }
    }

    linux {
        root-inputs += install/99-alchitry.rules -> /etc/udev/rules.d/99-alchitry.rules
        symlinks += ${app.linux.prefix}/bin/alchitry -> ${app.linux.install-path}/bin/alchitry
    }

    site {
        github {
            // oauth-token = ${env.GITHUB_TOKEN} // set in conveyor-local-beta.conf
            pages-branch = "gh-pages"
        }
    }
}