include "#!./gradlew -q printConveyorConfig"

app {
    vendor = Alchitry
    license = "GPL-3.0-only"
    description = "Write, build, and load projects for Alchitry FPGA development boards"
    contact-email = "support@alchitry.com"
    file-associations = [ .alp ]

    machines = [windows.amd64, linux.amd64.glibc, mac.amd64, mac.aarch64]

    linux {
        desktop-file."Desktop Entry".Categories = "GTK;Development"

        amd64.inputs += {
            from = "includes/linux-x64"
            to = "/"
        }

        aarch64.inputs += {
            from = "includes/linux-arm64"
            to = "/"
        }
    }

    windows.amd64.inputs += {
        from = "includes/windows-x64"
        to = "/"
    }

    mac {
        deltas = 0 // TODO: Remove when conveyor bug fixed

        info-plist {
            LSMinimumSystemVersion = 13.0
        }

        amd64.inputs += {
            from = "includes/darwin-x64"
            to = "/"
        }

        aarch64.inputs += {
            from = "includes/darwin-arm64"
            to = "/"
        }
    }

    jvm {
        cli {
            alchitry {
                main-class = com.alchitry.labs2.CLIKt
            }
        }
    }
}

conveyor.compatibility-level = 21
//app.site.consistency-checks = warn