package com.alchitry.labs.hardware.pinout

object CuPinConverter : PinConverter {
    override fun AcfToFPGAPin(acfPin: String): String? =
        when (acfPin) {
            "A2" -> "M1"
            "A3" -> "L1"
            "A5" -> "J1"
            "A6" -> "J3"
            "A8" -> "G1"
            "A9" -> "G3"
            "A11" -> "E1"
            "A12" -> "D1"
            "A14" -> "C1"
            "A15" -> "B1"
            "A17" -> "D3"
            "A18" -> "C3"
            "A20" -> "A1"
            "A21" -> "A2"
            "A23" -> "A3"
            "A24" -> "A4"
            "A27" -> "A5"
            "A28" -> "C5"
            "A30" -> "D5"
            "A31" -> "C4"
            "A33" -> "D4"
            "A34" -> "E4"
            "A36" -> "F4"
            "A37" -> "F3"
            "A39" -> "H4"
            "A40" -> "G4"
            "A42" -> "H1"
            "A43" -> "H3"
            "A45" -> "K3"
            "A46" -> "K4"
            "A48" -> "N1"
            "A49" -> "P1"
            "B2" -> "A6"
            "B3" -> "A7"
            "B5" -> "A10"
            "B6" -> "A11"
            "B8" -> "C9"
            "B9" -> "C10"
            "B11" -> "A12"
            "B12" -> "B14"
            "B14" -> "C14"
            "B15" -> "D14"
            "B17" -> "E14"
            "B18" -> "E12"
            "B20" -> "F14"
            "B21" -> "G14"
            "B23" -> "H12"
            "B24" -> "J12"
            "B27" -> "H11"
            "B28" -> "G11"
            "B30" -> "G12"
            "B31" -> "F12"
            "B33" -> "F11"
            "B34" -> "E11"
            "B36" -> "D12"
            "B37" -> "D11"
            "B39" -> "C12"
            "B40" -> "C11"
            "B42" -> "D10"
            "B43" -> "D9"
            "B45" -> "D7"
            "B46" -> "D6"
            "B48" -> "C7"
            "B49" -> "C6"
            "C2" -> "M3"
            "C3" -> "M4"
            "C5" -> "L4"
            "C6" -> "L5"
            "C8" -> "M6"
            "C9" -> "M7"
            "C11" -> "L9"
            "C12" -> null
            "C14" -> null
            "C15" -> null
            "C17" -> null
            "C18" -> null
            "C20" -> null
            "C21" -> null
            "C23" -> null
            "C24" -> null
            "C27" -> null
            "C28" -> null
            "C30" -> null
            "C31" -> null
            "C33" -> null
            "C34" -> null
            "C36" -> null
            "C37" -> null
            "C39" -> "P10"
            "C40" -> "P9"
            "C42" -> "L8"
            "C43" -> "L6"
            "C45" -> "P5"
            "C46" -> "P4"
            "C48" -> "P3"
            "C49" -> "P2"
            "LED0" -> "J11"
            "LED1" -> "K11"
            "LED2" -> "K12"
            "LED3" -> "K14"
            "LED4" -> "L12"
            "LED5" -> "L14"
            "LED6" -> "M12"
            "LED7" -> "N14"
            "RESET" -> "P8"
            "CLOCK" -> "P7"
            "USB_RX" -> "P14"
            "USB_TX" -> "M9"
            "SPI_MOSI" -> "M11"
            "SPI_MISO" -> "P11"
            "SPI_SCK" -> "P12"
            "SPI_SS" -> "P13"
            else -> null
        }
}